// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwn_Z2M_-_WkdPepfVHWoXFBRfFakRMxM',
    appId: '1:923702042051:web:bbe315f9a3bc0ce94c3176',
    messagingSenderId: '923702042051',
    projectId: 'cognivia-f7979',
    authDomain: 'cognivia-f7979.firebaseapp.com',
    databaseURL:
        'https://cognivia-f7979-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cognivia-f7979.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA73VKAIC1narFX9XPrunR2HhyxXhhWcI8',
    appId: '1:923702042051:android:dbcc43c32a108a514c3176',
    messagingSenderId: '923702042051',
    projectId: 'cognivia-f7979',
    databaseURL:
        'https://cognivia-f7979-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cognivia-f7979.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeTSwGGMCFczpus4BU3EsutUfeFzeKyFw',
    appId: '1:923702042051:ios:46b89e1f3bf7604f4c3176',
    messagingSenderId: '923702042051',
    projectId: 'cognivia-f7979',
    databaseURL:
        'https://cognivia-f7979-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cognivia-f7979.firebasestorage.app',
    iosBundleId: 'com.example.cognivia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeTSwGGMCFczpus4BU3EsutUfeFzeKyFw',
    appId: '1:923702042051:ios:46b89e1f3bf7604f4c3176',
    messagingSenderId: '923702042051',
    projectId: 'cognivia-f7979',
    databaseURL:
        'https://cognivia-f7979-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cognivia-f7979.firebasestorage.app',
    iosBundleId: 'com.example.cognivia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwn_Z2M_-_WkdPepfVHWoXFBRfFakRMxM',
    appId: '1:923702042051:web:6e5d1feb058f25424c3176',
    messagingSenderId: '923702042051',
    projectId: 'cognivia-f7979',
    authDomain: 'cognivia-f7979.firebaseapp.com',
    databaseURL:
        'https://cognivia-f7979-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cognivia-f7979.firebasestorage.app',
  );
}
